# Generated by Django 3.0 on 2021-09-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=60)),
                ('Price', models.CharField(max_length=60)),
                ('GST_percentage', models.CharField(choices=[('1', '0%'), ('2', '5%'), ('3', '12%'), ('4', '18%'), ('5', '28%')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Catelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=60)),
                ('Item_pic', models.FileField(upload_to='')),
                ('Item_selling_price', models.FloatField(max_length=60)),
                ('Item_discount', models.FloatField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Create_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.CharField(default=1, max_length=60)),
                ('Time', models.TimeField(blank=True, max_length=255, null=True, verbose_name='Time')),
                ('Date', models.DateField(blank=True, max_length=25, null=True, verbose_name='Date')),
                ('Toal_Amt', models.CharField(max_length=60)),
                ('Item_Name', models.CharField(max_length=60)),
                ('Phone_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Phone_number', models.CharField(blank=True, error_messages={'unique': 'This mobile no is already registered.'}, max_length=10, null=True, unique=True)),
                ('Pincode', models.CharField(max_length=60)),
                ('Customer_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sales_person_Name', models.CharField(max_length=60)),
                ('Sales_person_Identity', models.FileField(upload_to='')),
                ('Sales_person_Phone_number', models.CharField(blank=True, error_messages={'unique': 'This mobile no is already registered.'}, max_length=10, null=True, unique=True)),
                ('Sales_person_Image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(blank=True, error_messages={'unique': 'This mobile no is already registered.'}, max_length=10, null=True, unique=True)),
                ('OTP', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='marketing_profile',
            name='Employee_no',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Shop_name', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=60)),
                ('Pincode', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('Town', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIVIEW.Signup')),
            ],
        ),
    ]
