# Generated by Django 3.0 on 2021-09-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0002_auto_20210909_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='Cities',
        ),
    ]
