# Generated by Django 3.0 on 2021-09-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIVIEW', '0003_auto_20210916_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Cities',
            new_name='City',
        ),
    ]
